spring:
  h2:
    console:
      enabled: true
      path: '/console'
  datasource:
    url: 'jdbc:h2:file:/home/lukasz/Downloads/football-league/football-league-db'
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /status
keycloak:
  auth-server-url: 'http://localhost:8180/auth'
  realm: 'FootballLeague'
  resource: 'football-league-client'
  public-client: true



